# database
DATABASE_NAME:
  onboarding-assignment
DATABASE_CONNECTION_URL:
  mongodb://127.0.0.1:27017

# server
PORT:
  3000
HOST:
  127.0.0.1

# rabbitmq
RMQ_JOB_QNAME:
  onboarding-assignment-job-queue
RMQ_STATUS_QNAME:
  onboarding-assignment-db-update
RMQ_CONNECTION_URL:
  amqp://localhost

# redis
REDIS_HOST:
  redis://127.0.0.1
REDIS_PORT:
  6379