# database
DATABASE_NAME:
  onboarding-assignment
DATABASE_CONNECTION_URL:
  mongodb://127.0.0.1:27017
DATABASE_COLLECTION_NAME:
  jobmodels

# server
PORT:
  3000
HOST:
  127.0.0.1

# rabbitmq
RMQ_JOB_QNAME:
  onboarding-assignment-job-queue
RMQ_CONNECTION_URL:
  amqp://localhost

# redis
REDIS_HOST:
  127.0.0.1
REDIS_PORT:
  6379